# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(885, 510)
        self.label_cheie = QtWidgets.QLabel(Dialog)
        self.label_cheie.setGeometry(QtCore.QRect(0, 10, 161, 20))
        self.label_cheie.setObjectName("label_cheie")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 240, 241, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_criptare = QtWidgets.QPushButton(Dialog)
        self.pushButton_criptare.setGeometry(QtCore.QRect(620, 240, 171, 28))
        self.pushButton_criptare.setObjectName("pushButton_criptare")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 470, 251, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.listWidget_framework = QtWidgets.QListWidget(Dialog)
        self.listWidget_framework.setGeometry(QtCore.QRect(350, 320, 181, 141))
        self.listWidget_framework.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.listWidget_framework.setProperty("showDropIndicator", False)
        self.listWidget_framework.setObjectName("listWidget_framework")
        self.labelAlgo = QtWidgets.QLabel(Dialog)
        self.labelAlgo.setGeometry(QtCore.QRect(310, 20, 131, 16))
        self.labelAlgo.setObjectName("labelAlgo")
        self.label_fisier = QtWidgets.QLabel(Dialog)
        self.label_fisier.setGeometry(QtCore.QRect(620, 20, 131, 16))
        self.label_fisier.setObjectName("label_fisier")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 240, 317, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_add_cheie = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_add_cheie.setObjectName("pushButton_add_cheie")
        self.verticalLayout.addWidget(self.pushButton_add_cheie)
        self.pushButton_actualizare_cheie = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_actualizare_cheie.setObjectName("pushButton_actualizare_cheie")
        self.verticalLayout.addWidget(self.pushButton_actualizare_cheie)
        self.pushButton_stergere_cheie = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_stergere_cheie.setObjectName("pushButton_stergere_cheie")
        self.verticalLayout.addWidget(self.pushButton_stergere_cheie)
        self.listWidget_chei = QtWidgets.QListWidget(Dialog)
        self.listWidget_chei.setGeometry(QtCore.QRect(0, 40, 256, 192))
        self.listWidget_chei.setObjectName("listWidget_chei")
        self.listWidget_algoritmi = QtWidgets.QListWidget(Dialog)
        self.listWidget_algoritmi.setGeometry(QtCore.QRect(310, 40, 256, 192))
        self.listWidget_algoritmi.setObjectName("listWidget_algoritmi")
        self.listWidget_fisiere = QtWidgets.QListWidget(Dialog)
        self.listWidget_fisiere.setGeometry(QtCore.QRect(620, 40, 256, 192))
        self.listWidget_fisiere.setObjectName("listWidget_fisiere")
        self.label_framework = QtWidgets.QLabel(Dialog)
        self.label_framework.setGeometry(QtCore.QRect(350, 300, 171, 20))
        self.label_framework.setObjectName("label_framework")
        self.pushButton_criptare_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_criptare_2.setGeometry(QtCore.QRect(610, 280, 171, 28))
        self.pushButton_criptare_2.setObjectName("pushButton_criptare_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton_add_cheie, self.pushButton_stergere_cheie)
        Dialog.setTabOrder(self.pushButton_stergere_cheie, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.pushButton_criptare)
        Dialog.setTabOrder(self.pushButton_criptare, self.listWidget_framework)
        Dialog.setTabOrder(self.listWidget_framework, self.pushButton_5)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ProiectSI"))
        self.label_cheie.setText(_translate("Dialog", "Chei/Perechi disponibile:"))
        self.pushButton_3.setText(_translate("Dialog", "Adăugare algoritm nou suportat cu\n"
"framework-ul și cheia selectate"))
        self.pushButton_criptare.setText(_translate("Dialog", "Criptare fișier"))
        self.pushButton_5.setText(_translate("Dialog", "Comparare performanță framework-uri"))
        self.labelAlgo.setText(_translate("Dialog", "Algoritmi disponibili:"))
        self.label_fisier.setText(_translate("Dialog", "Fișiere gestionate:"))
        self.pushButton_add_cheie.setText(_translate("Dialog", "Adăugare cheie/pereche"))
        self.pushButton_actualizare_cheie.setText(_translate("Dialog", "Actualizare cheie/pereche selectată"))
        self.pushButton_stergere_cheie.setText(_translate("Dialog", "Ștergere cheie/pereche selectată din baza de date"))
        self.label_framework.setText(_translate("Dialog", "Framework-uri disponibile:"))
        self.pushButton_criptare_2.setText(_translate("Dialog", "Decriptare fișier selectat"))
